"""add users and credentials

Revision ID: 0200cd0b0ea0
Revises: 5ca6e1b9f324
Create Date: 2026-10-02 19:46:01.167980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0200cd0b0ea0'
down_revision: Union[str, Sequence[str], None] = '5ca6e1b9f324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###