"""add organization device and login events

Revision ID: e108d3554667
Revises: bc000c95ae6d
Create Date: 2026-10-04 16:43:36.229067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e108d3554667'
down_revision: Union[str, Sequence[str], None] = 'bc000c95ae6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('login_success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_login_events_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_login_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_events'))
    )
    op.create_index(op.f('ix_login_events_device_id'), 'login_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_login_events_organization_id'), 'login_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_login_events_user_id'), 'login_events', ['user_id'], unique=False)
    op.add_column('devices', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_devices_user_id_users'), 'devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_devices_organization_id_organizations'), 'devices', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_organization_id_organizations'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_user_id_users'), 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_column('devices', 'organization_id')
    op.drop_index(op.f('ix_login_events_user_id'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_organization_id'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_device_id'), table_name='login_events')
    op.drop_table('login_events')
    # ### end Alembic commands ###